general:
  plot_filetype: ".png"
  ts_index_name: "id_ts"
  scal_index_name: "id_scal"

labels: de

build_datapackage:
  el_gas_relation: electricity_gas_relation  # appears in optimize as well
  emission: emission
  additional_scalars_file: additional_scalars.csv

optimize:
  filename_metadata: datapackage.json
  solver: cbc
  solve_kwargs:
    tee: True
    keepfiles: True
  cmdline_options:
    AllowableGap: 0.01
  debug: true
  receive_duals: false
  el_gas_relation: electricity_gas_relation  # appears in build_datapackage as well
  el_key: electricity  # prefix of keywords for gas electricity relation
  gas_key: gas  # prefix of keywords for gas electricity relation


plot_scalar_results:
  agg_regions: true
  tick_label_size: 12

prepare_cop_timeseries:
  quality_grade: 0.4
  scenario: "ALL"

prepare_electricity_demand:
  REGIONS: ["BB", "B"]
  TS_VAR_UNIT: "None"
  TS_SOURCE: "https://data.open-power-system-data.org/time_series/2020-10-06"
  TS_COMMENT: "DE_50hertz actual load data"
  COL_SELECT:  "DE_50hertz_load_actual_entsoe_transparency"
prepare_feedin:
  YEARS: list(range(2010, 2020))
  # specific to wind and pv time series
  NUTS_DE30: "DE30"
  NUTS_DE40: "DE40"
  RENAME_NUTS: {NUTS_DE30: "B", NUTS_DE40: "BB" }
  TS_VAR_UNIT: "None"
  TS_SOURCE: "https://www.renewables.ninja/"
  TS_COMMENT: "navigate to country Germany"
  # specific to ror time series
  REGIONS: ["BB", "B"]
  TS_SOURCE_ROR: "https://zenodo.org/record/1044463"
  TS_COMMENT_ROR: "Isolated ror availability time series from DIW data"
